const booksData = [
  {
    title: "图书馆空间再造：公共文化新趋势",
    author: "李若楠 等",
    category: "图书馆学",
    tags: ["图书馆设计", "公共文化", "阅读空间"],
    summary: "梳理国内外公共图书馆的空间更新案例，从规划布局、亲子阅读区、无障碍服务到复合功能引入，为馆舍改造提供实践指引。",
    publisher: "中国建筑工业出版社",
    year: 2023,
    isbn: "978-7-112-30125-6",
    callNumber: "G258/45",
    availability: "国家图书馆·综合借阅区 / 多地省市公共图书馆馆藏"
  },
  {
    title: "儿童阅读力培养：0-12岁书单与方法",
    author: "张颖",
    category: "亲子教育",
    tags: ["儿童阅读", "亲子共读", "绘本推荐"],
    summary: "按照年龄段推荐300余册绘本与桥梁书，配套家庭阅读计划与图书馆借阅建议，适合亲子阅读指导。",
    publisher: "新星出版社",
    year: 2022,
    isbn: "978-7-5133-4510-8",
    callNumber: "G613/12",
    availability: "北京市少年儿童图书馆 / 各地亲子阅读专区"
  },
  {
    title: "城市阅读地图：公共文化服务观察",
    author: "全国公共图书馆联盟",
    category: "城市研究",
    tags: ["城市规划", "文化服务", "阅读推广"],
    summary: "通过对15座城市的阅读人口、馆藏密度、文化空间布局进行数据分析，呈现城市阅读生态全景。",
    publisher: "社会科学文献出版社",
    year: 2024,
    isbn: "978-7-5201-9876-3",
    callNumber: "G258.6/21",
    availability: "上海图书馆·研究阅览室 / 各地高校图情专业馆藏"
  },
  {
    title: "书店经营的100个细节",
    author: "陈诺",
    category: "文化创意",
    tags: ["独立书店", "运营管理", "空间营销"],
    summary: "从选址、书单策划、活动设计到会员运营，结合全国知名书店案例解析复合型书店的经营策略。",
    publisher: "中信出版社",
    year: 2021,
    isbn: "978-7-5086-9888-5",
    callNumber: "F724.6/18",
    availability: "钟书阁·专业资源区 / 文化创意园区共享图书馆"
  },
  {
    title: "高校图书馆信息素养课程设计",
    author: "刘晨光",
    category: "信息素养",
    tags: ["高校图书馆", "信息检索", "课程设计"],
    summary: "提供一学期信息素养必修课的教学设计、评价指标与案例练习，适用于高校图情教师与馆员培训。",
    publisher: "高等教育出版社",
    year: 2020,
    isbn: "978-7-0403-2105-2",
    callNumber: "G252.7/09",
    availability: "复旦大学图书馆·教学支持中心"
  },
  {
    title: "东亚古籍修复与保护指南",
    author: "故宫博物院图书馆",
    category: "古籍保护",
    tags: ["古籍修复", "文献保护", "非遗技艺"],
    summary: "系统介绍纸质古籍的病害诊断、材料选择与修复流程，配合图示记录传统工艺。",
    publisher: "文物出版社",
    year: 2021,
    isbn: "978-7-5010-6521-4",
    callNumber: "K877/05",
    availability: "国家图书馆·文献修复中心"
  },
  {
    title: "社区阅读空间的设计与实践",
    author: "赵晨",
    category: "社区文化",
    tags: ["社区图书馆", "空间设计", "公共服务"],
    summary: "围绕社区图书馆、共享书房、流动书车的运营模式进行案例分析，给出社区共建阅读空间的操作手册。",
    publisher: "江苏人民出版社",
    year: 2023,
    isbn: "978-7-214-28066-9",
    callNumber: "G258.2/33",
    availability: "南京市图书馆·社区服务部"
  },
  {
    title: "中文信息检索与知识组织",
    author: "王一凡",
    category: "知识组织",
    tags: ["元数据", "主题分析", "数字人文"],
    summary: "结合最新的中文分词、知识图谱与主题标引实践，介绍图书馆如何构建可拓展的知识组织系统。",
    publisher: "科学出版社",
    year: 2024,
    isbn: "978-7-03-076532-1",
    callNumber: "G250.2/66",
    availability: "武汉大学信息管理学院图书馆"
  },
  {
    title: "馆校合作阅读项目案例精选",
    author: "上海市中小学图书馆联盟",
    category: "阅读推广",
    tags: ["馆校合作", "阅读推广", "课程融合"],
    summary: "汇总上海地区30个馆校合作阅读项目，提供项目设计、实施步骤与效果评估表格，可直接复用。",
    publisher: "华东师范大学出版社",
    year: 2022,
    isbn: "978-7-5675-9188-2",
    callNumber: "G658/41",
    availability: "上海少年儿童图书馆·活动资源区"
  },
  {
    title: "数字人文实验室：图书馆的跨界实践",
    author: "王子涵",
    category: "数字人文",
    tags: ["数字化转型", "跨学科", "科研支持"],
    summary: "介绍高校与公共图书馆如何搭建数字人文实验室，从技术栈、项目管理到跨部门协同的操作指南。",
    publisher: "上海科技教育出版社",
    year: 2024,
    isbn: "978-7-5470-2368-4",
    callNumber: "G250.7/12",
    availability: "上海图书馆·创新实践中心"
  },
  {
    title: "AI 辅助编目：流程与案例",
    author: "中国图书馆学会编目委员会",
    category: "知识组织",
    tags: ["人工智能", "编目", "标准化"],
    summary: "汇集国内外图书馆在 AI 自动分类、著录与主题分析方面的实验与评估，附带实施路线图。",
    publisher: "中国标准出版社",
    year: 2023,
    isbn: "978-7-5066-9221-0",
    callNumber: "G252.7/31",
    availability: "国家图书馆·技术服务部"
  },
  {
    title: "少数民族语言文献守护计划",
    author: "国家民委文化发展中心",
    category: "文献保护",
    tags: ["民族文献", "口述史", "数字保存"],
    summary: "记录藏羌彝、维吾尔、蒙古等语言文献的采集、整理与数字化工作，提供标准化流程与案例分享。",
    publisher: "民族出版社",
    year: 2021,
    isbn: "978-7-105-12258-1",
    callNumber: "G258.2/65",
    availability: "四川省图书馆·民族文献中心"
  },
  {
    title: "乡村图书馆共建指南",
    author: "刘佳音",
    category: "乡村振兴",
    tags: ["乡村阅读", "社区共建", "志愿服务"],
    summary: "梳理乡村图书馆筹建流程、捐赠体系与志愿者管理模式，附带 12 个县域案例。",
    publisher: "中国农业出版社",
    year: 2022,
    isbn: "978-7-109-27053-7",
    callNumber: "G258.6/52",
    availability: "贵州省图书馆·乡村振兴书屋联盟"
  },
  {
    title: "馆配选书策略：数据驱动的采购决策",
    author: "盛雨辰",
    category: "资源建设",
    tags: ["图书采购", "数据分析", "用户画像"],
    summary: "解析读者画像、借阅数据与出版趋势如何协同决定馆配选书策略，提供可直接复用的指标模板。",
    publisher: "商务印书馆",
    year: 2023,
    isbn: "978-7-100-20234-8",
    callNumber: "G252/81",
    availability: "浙江图书馆·资源建设部"
  },
  {
    title: "阅读疗愈：图书馆的心理健康服务",
    author: "孙雅雯",
    category: "阅读推广",
    tags: ["书疗", "心理服务", "馆员培训"],
    summary: "介绍阅读疗愈项目的策划、心理学基础与风险控制，包含面向青少年与老年人的服务方案。",
    publisher: "华东师范大学出版社",
    year: 2024,
    isbn: "978-7-5675-9980-2",
    callNumber: "G258.6/73",
    availability: "上海市心理健康图书馆"
  },
  {
    title: "高校馆嵌入式教学案例精选",
    author: "陈曦",
    category: "信息素养",
    tags: ["课程融合", "学科馆员", "教学评估"],
    summary: "呈现 15 个高校学科馆员与院系教师合作的嵌入式教学案例，附课程大纲与评价表。",
    publisher: "高等教育出版社",
    year: 2021,
    isbn: "978-7-0403-2158-8",
    callNumber: "G252.7/25",
    availability: "南京大学图书馆·教学发展中心"
  },
  {
    title: "智慧图书馆物联网实践",
    author: "李淼",
    category: "智慧服务",
    tags: ["物联网", "RFID", "自动化"],
    summary: "解析智慧图书馆在座位管理、自动分拣、能源管理中的物联网应用，提供建设方案与成本测算。",
    publisher: "电子工业出版社",
    year: 2022,
    isbn: "978-7-121-43215-6",
    callNumber: "G251/33",
    availability: "深圳图书馆·智慧运行中心"
  },
  {
    title: "少儿阅读空间色彩设计",
    author: "童梦实验室",
    category: "空间设计",
    tags: ["儿童友好", "色彩心理", "场景搭建"],
    summary: "通过 200 张实景照片展示亲子阅读空间的色彩与材质搭配，配套安全与照明标准。",
    publisher: "广西师范大学出版社",
    year: 2023,
    isbn: "978-7-5495-9930-4",
    callNumber: "G613/28",
    availability: "广州少年儿童图书馆·设计资料室"
  },
  {
    title: "图书馆可持续运营手册",
    author: "IFLA 绿色图书馆工作组",
    category: "可持续发展",
    tags: ["碳中和", "绿色建筑", "环境教育"],
    summary: "结合国际绿色图书馆奖案例，提供能源、材料、垃圾分类与读者参与的全链路指南。",
    publisher: "人民邮电出版社",
    year: 2022,
    isbn: "978-7-115-58532-9",
    callNumber: "G258/88",
    availability: "深圳大学图书馆·可持续发展专区"
  },
  {
    title: "声像档案数字化操作规范",
    author: "中国传媒大学图书馆",
    category: "数字化",
    tags: ["音视频", "数字保存", "编目"],
    summary: "详解广播影视声像档案的采集、转码与版权处理，附常见问题排查手册。",
    publisher: "中国广播影视出版社",
    year: 2021,
    isbn: "978-7-5060-9821-4",
    callNumber: "G253/59",
    availability: "中国传媒大学图书馆·媒资中心"
  },
  {
    title: "青少年编程图书分级导引",
    author: "杨青",
    category: "馆藏建设",
    tags: ["STEAM", "分级阅读", "选书指南"],
    summary: "针对 8-18 岁读者梳理编程与创客图书的选购标准，提供项目式阅读活动模板。",
    publisher: "人民邮电出版社",
    year: 2024,
    isbn: "978-7-115-59001-9",
    callNumber: "TP3/98",
    availability: "深圳少儿图书馆·科技创新空间"
  },
  {
    title: "图书馆志愿者管理实务",
    author: "北京阅读推广中心",
    category: "志愿服务",
    tags: ["志愿者", "培训体系", "服务设计"],
    summary: "覆盖招募、培训、激励与评估的闭环流程，提供 30 套志愿岗位说明书范本。",
    publisher: "北京联合出版公司",
    year: 2022,
    isbn: "978-7-5596-6100-5",
    callNumber: "G258.6/14",
    availability: "首都图书馆·社会教育部"
  },
  {
    title: "馆员数据素养快速入门",
    author: "赵铭",
    category: "专业发展",
    tags: ["数据分析", "工具", "职业培训"],
    summary: "通过 12 个实操案例讲解 Excel、Power BI 与 Python 在馆务分析中的应用。",
    publisher: "机械工业出版社",
    year: 2023,
    isbn: "978-7-111-72368-2",
    callNumber: "G258.7/43",
    availability: "武汉图书馆·馆员发展中心"
  },
  {
    title: "无障碍阅读产品设计手册",
    author: "中国盲文出版社",
    category: "无障碍服务",
    tags: ["盲文", "有声书", "信息无障碍"],
    summary: "针对视障群体介绍盲文、点显、语音与图像描述等无障碍服务产品的设计规范。",
    publisher: "中国盲文出版社",
    year: 2021,
    isbn: "978-7-5320-8765-0",
    callNumber: "G258.6/08",
    availability: "中国盲文图书馆·信息无障碍实验室"
  },
  {
    title: "馆际互借与文献传递实务",
    author: "全国高校图书馆文献传递中心",
    category: "资源共享",
    tags: ["馆际互借", "联盟合作", "流程优化"],
    summary: "梳理馆际互借网络的组织架构、收费模式与服务流程，提供 SLA 模板与案例。",
    publisher: "南京大学出版社",
    year: 2021,
    isbn: "978-7-305-23019-8",
    callNumber: "G255/44",
    availability: "CALIS 管理中心"
  },
  {
    title: "高校阅览空间改造工作手册",
    author: "天津大学建筑设计研究院",
    category: "空间更新",
    tags: ["校园阅读", "建筑改造", "功能分区"],
    summary: "总结高校阅览空间改造的调研、动线规划与施工管理经验，配套预算清单。",
    publisher: "天津大学出版社",
    year: 2023,
    isbn: "978-7-5618-7420-1",
    callNumber: "TU201/15",
    availability: "天津大学图书馆·基建改造项目组"
  },
  {
    title: "馆舍应急管理与安全演练",
    author: "中国图书馆学会安全委员会",
    category: "运营管理",
    tags: ["安全演练", "风险管理", "应急预案"],
    summary: "涵盖消防、洪水、疫情等突发情况的应急预案编制要点，并附演练记录模板。",
    publisher: "中国标准出版社",
    year: 2022,
    isbn: "978-7-5066-9333-0",
    callNumber: "G258/93",
    availability: "国家图书馆·安全管理办公室"
  },
  {
    title: "图书馆 XR 互动体验设计",
    author: "周南",
    category: "创新服务",
    tags: ["沉浸式体验", "XR", "教育科技"],
    summary: "解析虚拟现实、增强现实在图书馆展览与教育中的应用流程，附硬件选型建议。",
    publisher: "科学出版社",
    year: 2024,
    isbn: "978-7-03-077210-7",
    callNumber: "TP391.9/26",
    availability: "成都图书馆·数字体验中心"
  },
  {
    title: "数字藏品与文化 IP 授权",
    author: "国家图书馆数字文化研究院",
    category: "数字资产",
    tags: ["数字藏品", "版权", "文创"],
    summary: "探讨图书馆数字藏品的版权策略、平台合作与商业化模式，附项目评估框架。",
    publisher: "生活·读书·新知三联书店",
    year: 2023,
    isbn: "978-7-108-07720-5",
    callNumber: "G256/67",
    availability: "国家图书馆·数字文化研究院"
  }
  ];

if (typeof globalThis !== "undefined") {
  globalThis.booksData = booksData;
}
